# Asking basic questions to your Data

In [20]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("../datasets/titanic.csv")

### 1. Check the data size - rows x columns?

In [7]:
df.shape

(1309, 14)

### 2. Check the sample data?

In [9]:
df.sample(5) # instead of head use sample to see the random X records instead of top X records

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
332,2,0,"Baimbrigge, Mr. Charles Robert",male,23.0,0,0,C.A. 31030,10.500,NaN,S,NaN,NaN,Guernsey
1162,3,1,"Ryan, Mr. Edward",male,NaN,0,0,383162,7.750,NaN,Q,14,NaN,NaN
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.000,NaN,S,NaN,NaN,NaN
828,3,0,"Goodwin, Miss. Jessie Allis",female,10.0,5,2,CA 2144,46.900,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY"
252,1,0,"Ryerson, Mr. Arthur Larned",male,61.0,1,3,PC 17608,262.375,B57,C,NaN,NaN,"Haverford, PA / Cooperstown, NY"

### 3. Check the data type of the cols?

In [12]:
df.info() # You can also see the memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB

### 4. Check for the missing values

In [14]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

### 5. Check 'Measures of Central Tendency' and 'Measures of Variability(Spread)'

In [15]:
df.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

### 6. Check for duplicates

In [18]:
df.duplicated().sum()

0

### 7. How is the correlation between cols?

In [21]:
df.select_dtypes(include=np.number).corr()

            pclass  survived       age     sibsp     parch      fare      body
pclass    1.000000 -0.312469 -0.408106  0.060832  0.018322 -0.558629 -0.034642
survived -0.312469  1.000000 -0.055513 -0.027825  0.082660  0.244265       NaN
age      -0.408106 -0.055513  1.000000 -0.243699 -0.150917  0.178739  0.058809
sibsp     0.060832 -0.027825 -0.243699  1.000000  0.373587  0.160238 -0.099961
parch     0.018322  0.082660 -0.150917  0.373587  1.000000  0.221539  0.051099
fare     -0.558629  0.244265  0.178739  0.160238  0.221539  1.000000 -0.043110
body     -0.034642       NaN  0.058809 -0.099961  0.051099 -0.043110  1.000000